### ISSUE TITLE
POST parameters are not minimized

### ISSUE THREAD

**Issue by ngregoire** [ngo/burp-request-minimizer#7]
There's a bug at [line 77](
https://github.com/PortSwigger/request-minimizer/blob/f101564d759d876281a5c861f78f7d389f0b0e2b/minimizer.py#L77) of the _minimize() function. The IF condition is incorrect, and POST parameters (aka PARAM_BODY) are never minimized:

    if param_type in [IParameter.PARAM_URL, IParameter.PARAM_BODY and IParameter.PARAM_COOKIE]:

Fix (replacing `and`by `,`):

    if param_type in [IParameter.PARAM_URL, IParameter.PARAM_BODY, IParameter.PARAM_COOKIE]:

**Comment by ngo** [comment]
Thanks @ngregoire! What a silly bug :/

**Comment by ngregoire** [comment]
You're welcome! To be honest, I don't know how I missed this bug for so long... #FacePalm
And thanks for the prompt patch
